<footer class="site-footer">
  <div class="container">
      <div class="content row">
          <div class="footer-menu row col-fix">
              <div class="col-md-6 col-md-push-3 col-xs-12 icgc-footer">
                  <img class="md-icon-footer" src="assets/images/ICGC_Logo_Footer.svg">
                  <h3 class="footer">International Cancer Genome Consortium</h3>
                  <div class="two-column">
                      <div class="col-1">
                          <ul>
                              <li><a href="cgp.html">Cancer Genome Projects</a></li>
                              <li><a href="research.html">Research</a></li>
                              <li><a href="policies-and-guidelines-intro.html">Policies & Guidelines</a></li>
                              <li><a href="about.html">About Us</a></li>
                          </ul>
                      </div>
                      <div class="col-2">
                          <ul>
                              <li><a href="contact-us.html">Contact Us</a></li>
                              <li><a href="#">Terms & Conditions</a></li>
                              <li><a href="#">Privacy Policy</a></li>
                          </ul>
                      </div>
                  </div>
                  <p>&#169; 2012 International Cancer Genome Consortium. All rights reserved.</p>
              </div>
              <div class="col-md-3 col-md-pull-6 col-xs-6 dcc-footer">
                  <img class="sm-icon-footer" src="assets/images/icon-data-portal-footer.svg">
                  <h3 class="footer">ICGC Data Portal (DCC)</h3>
                  <ul>
                      <li><a href="#">DCC Cancer Projects</a></li>
                      <li><a href="#">DCC Advanced Research</a></li>
                      <li><a href="#">DCC Data Repository</a></li>
                      <li><a href="#">DCC Documentation</a></li>
                      <li><a href="#">DCC Data Submission</a></li>
                  </ul>
              </div>
              <div class="col-md-3 col-xs-6 daco-footer">
                  <img class="sm-icon-footer" src="assets/images/icon-open-access-footer.svg">
                  <h3 class="footer">Data Access Compliance Office (DACO)</h3>
                  <ul>
                      <li><a href="controlled-data-access.html">Controlled Data Access</a></li>
                      <li><a href="#">DACO Application</a></li>
                      <li><a href="#">DACO Help Guides</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>

</footer>
