<head>
  <title>International Cancer Genome Consortium</title>

    <!-- Required meta tags always come first -->
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type">

    <!-- Required for IE mobile -->
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- Favicon -->
	<link href="favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- FontAwesome CSS -->
	<link href="assets/FontAwesome/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css">

    <!-- Bootstrap CSS -->
	<link href="assets/bootstrap/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css">

    <!-- Base CSS -->
    <link href="assets/css/icgc-bootstrap.css" media="all" rel="stylesheet" type="text/css">
    <link href="assets/css/screen.css" media="all" rel="stylesheet" type="text/css">

    <!-- Theme: Page CSS -->
    <link href="assets/css/homepage.css" media="all" rel="stylesheet" type="text/css">
    <link href="assets/css/cgp-cards.css" media="all" rel="stylesheet" type="text/css">

    <!-- Additional CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Open+Sans:400,400i,600,600i,700" rel="stylesheet">
